---
- hosts: thewalke.rs
  tasks:
    - name: Install ansible dependencies
      apt:
        name:
          - python-selinux
          - python-docker
          - python3-selinux
          - python3-docker
          - python-pip
          - python3-pip
        state: present
      become: yes

    - name: Install pip dependencies
      pip:
        name: docker-compose
        state: present
      become: yes

- hosts: thewalke.rs
  roles:
    - name: hardening
      become: yes

    - name: geerlingguy.docker
      become: yes

- hosts: thewalke.rs
  vars:
    database_url: "{{ lookup('env', 'DATABASE_URL') }}"
    image_name: srwalker101/whatson-ingest:latest
  tasks:
    - name: Deploy the nginx config
      template:
        src: whatson.conf
        dest: /etc/nginx/sites-available/whatson
        owner: root
        group: root
      become: yes
      notify: Restart nginx

    - name: Link the config file to the correct place
      file:
        src: /etc/nginx/sites-available/whatson
        dest: /etc/nginx/sites-enabled/whatson
        state: link
      become: yes
      notify: Restart nginx

    - name: Run the web app
      docker_container:
        image: srwalker101/whatson-web
        name: whatson-web
        network_mode: host
        pull: true
        restart_policy: always
        env:
          DATABASE_URL: "{{ lookup('env', 'DATABASE_URL') }}"
      become: yes

    - name: Fetch the ingest container
      docker_image:
        name: srwalker101/whatson-ingest
        state: present
        source: pull
        force_source: yes
      become: yes

    - name: Copy the ingest service
      template:
        src: whatson-ingest.service
        dest: /etc/systemd/system/whatson-ingest.service
        owner: root
        group: root
      become: yes
      notify: Reload systemd

    - name: Copy the ingest timer
      template:
        src: whatson-ingest.timer
        dest: /etc/systemd/system/whatson-ingest.timer
        owner: root
        group: root
      become: yes
      notify: Reload systemd

    - name: Enable the timer
      systemd:
        name: whatson-ingest.timer
        state: started
        enabled: yes
      become: yes

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      become: yes
